---
- hosts: localhost
  become: true

  tasks:
    - name: Install Docker from repository
      apt:
       name: docker
       state: present

    - name: Install Docker from repository 
      apt:
       name: docker.io
       state: present

    - name: Install pip3 package
      package:
        update_cache: yes 
        name: python3-pip
        state: latest

    - name: Install Docker SDK for Python
      pip:
       name: docker
       executable: pip3

    - name: Build Nginx Docker container 
      community.docker.docker_image:
        build: 
          path: ./nginx-docker
        name: nginx
        tag: v1
        source: build 

    - name: Build Flask Docker container 
      community.docker.docker_image:
        build: 
          path: ./app
        name: flask
        tag: v1
        source: build 

    - name: Create a network
      community.docker.docker_network:
        name: flask
    
    - name: Run Flask1
      docker_container:
         name: flask1
         image: flask:v1 
         state: started
         exposed_ports: 5000
         networks:
           - name: flask

    - name: Run Flask2
      docker_container:
         name: flask2
         image: flask:v1
         state: started
         exposed_ports: 5000
         networks:
           - name: flask
    
    - name: Run Nginx
      docker_container:
         name: nginx
         image: nginx:v1 
         state: started
         published_ports: "80:80"
         exposed_ports: 80
         networks:
           - name: flask
