---
- hosts: localhost
  become: true

  tasks:
    - name: Install Docker from repository
      apt:
       name: docker
       state: present

    - name: Install Docker from repository 
      apt:
       name: docker.io
       state: present

    - name: Install pip3 package
      package:
        update_cache: yes 
        name: python3-pip
        state: latest

    - name: Install Docker SDK for Python
      pip:
       name: docker
       executable: pip3

    - name: Build Nginx Docker container 
      community.docker.docker_image:
        build: 
          path: ./nginx-docker
        name: nginx
        tag: v1
        source: build 
