---
- hosts: localhost
  become: true

  tasks:
    - name: install packages to allow apt to use a repository over HTTPS
      apt: name={{ item }} state=latest update_cache=yes
      loop: ['ca-certificates', 'curl', 'gnupg', 'lsb-release']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest


