---
- hosts: localhost
  become: true

  tasks:
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Install pip3 package
      package:
        update_cache: yes 
        name: python3-pip
        state: latest

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
    
    - name: Install Docker SDK for Python
      pip:
       name: docker
       executable: pip3
    
